"""Hybrid decision engine: mixed logit with LLM-elicited preference heterogeneity.

Combines literature-calibrated mean β coefficients with agent-specific
scaling factors from LLM-elicited 1–10 importance ratings. Each agent
gets a unique β vector:

    β_kᵢ = clamp(w_kᵢ / 0.25, 0.2, 4.0) × β̄_k

where β̄_k are the literature defaults and w_kᵢ are normalized weights
from the LLM's preference ratings for agent i's demographic profile.

This is a mixed logit specification (Train 2003) where the individual-
level heterogeneity is generated by an LLM acting as a synthetic survey
respondent (Argyle et al. 2023).

See docs/hybrid-mode.md for full methodology and literature citations.
"""

from __future__ import annotations

from agent_urban_planning.core.agents import Agent
from agent_urban_planning.decisions.base import ZoneChoice
from agent_urban_planning.decisions._legacy_singapore_utility import (
    UtilityEngine,
    _DEFAULT_BETA_PRICE_INCOME,
    _DEFAULT_BETA_COMMUTE,
    _DEFAULT_BETA_FACILITIES,
    _DEFAULT_BETA_AMENITY,
    _compute_facilities_density,
)
from agent_urban_planning.core.environment import Environment


# Scaling bounds to prevent degenerate β values.
# s ∈ [0.2, 4.0] means no β can be less than 20% or more than 400%
# of its literature value. In practice, realistic LLM ratings
# (e.g., 10/3/3/3) produce s_max ≈ 3.08, well within bounds.
_SCALE_MIN = 0.2
_SCALE_MAX = 4.0

# Equal-weight baseline: when all 4 dimensions have equal LLM ratings,
# each normalized weight = 0.25, so s = w/0.25 = 1.0 (no scaling).
_EQUAL_WEIGHT = 0.25


class HybridUtilityEngine(UtilityEngine):
    """Mixed logit engine with LLM-elicited agent-specific β scaling.

    Extends ``UtilityEngine`` by reading ``agent.preferences`` (set by
    ``LLMPreferenceElicitor`` before market clearing) and scaling the
    literature β coefficients per agent.

    When ``agent.preferences`` are equal (0.25 each) or unset, the
    literature defaults are used unchanged — so the engine degrades
    gracefully to homogeneous mode.
    """

    def decide(
        self,
        agent: Agent,
        environment: Environment,
        zone_options: list[str],
        prices: dict[str, float],
    ) -> ZoneChoice:
        # Compute agent-specific β by scaling literature defaults
        self._apply_agent_scaling(agent)

        # Delegate to the parent UtilityEngine.decide() which uses
        # self.beta_price_income, self.beta_commute, etc.
        result = super().decide(agent, environment, zone_options, prices)

        # Restore literature defaults for the next agent
        self._restore_defaults()

        return result

    def _apply_agent_scaling(self, agent: Agent) -> None:
        """Scale self.beta_* by the agent's preference weights."""
        prefs = agent.preferences
        w = [prefs.alpha, prefs.beta, prefs.gamma, prefs.delta]

        # If all weights are equal (0.25) or all zero, no scaling needed
        if all(abs(wi - _EQUAL_WEIGHT) < 1e-6 for wi in w):
            return

        # Compute and clamp scaling factors
        scales = [max(_SCALE_MIN, min(_SCALE_MAX, wi / _EQUAL_WEIGHT)) for wi in w]

        self.beta_price_income = scales[0] * _DEFAULT_BETA_PRICE_INCOME
        self.beta_commute = scales[1] * _DEFAULT_BETA_COMMUTE
        self.beta_facilities = scales[2] * _DEFAULT_BETA_FACILITIES
        self.beta_amenity = scales[3] * _DEFAULT_BETA_AMENITY

    def _restore_defaults(self) -> None:
        """Restore literature defaults after processing one agent."""
        self.beta_price_income = _DEFAULT_BETA_PRICE_INCOME
        self.beta_commute = _DEFAULT_BETA_COMMUTE
        self.beta_facilities = _DEFAULT_BETA_FACILITIES
        self.beta_amenity = _DEFAULT_BETA_AMENITY
